spring:
    datasource:
            dataSourceClassName: org.h2.Driver
            url: jdbc:h2:file:./data/app_db;DB_CLOSE_ON_EXIT=FALSE
            databaseName:
            serverName:
            username: 'sa'
            password: ''
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        openInView: false
        show_sql: true
        format_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            
        